// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApGr5ZybJkQ1_hLnPNXpfrtaT4qBivVoY',
    appId: '1:448343942111:web:850694499f387b32fa1a6a',
    messagingSenderId: '448343942111',
    projectId: 'last-task2',
    authDomain: 'last-task2.firebaseapp.com',
    storageBucket: 'last-task2.appspot.com',
    measurementId: 'G-9T987P1KHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWyerap1N3BbIt-xp1qAf0T-ZSDhKVUNw',
    appId: '1:448343942111:android:43230d97b3eb77dffa1a6a',
    messagingSenderId: '448343942111',
    projectId: 'last-task2',
    storageBucket: 'last-task2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFs5LNXAsVF339eAoqWConyccHQf37A2A',
    appId: '1:448343942111:ios:0b497813f167b8fafa1a6a',
    messagingSenderId: '448343942111',
    projectId: 'last-task2',
    storageBucket: 'last-task2.appspot.com',
    iosClientId: '448343942111-2256mpv1drpd7tn3j8d729lk4pgat7o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.heStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFs5LNXAsVF339eAoqWConyccHQf37A2A',
    appId: '1:448343942111:ios:0b497813f167b8fafa1a6a',
    messagingSenderId: '448343942111',
    projectId: 'last-task2',
    storageBucket: 'last-task2.appspot.com',
    iosClientId: '448343942111-2256mpv1drpd7tn3j8d729lk4pgat7o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.heStore',
  );
}
